---
- name: get replication lag
  shell: sleep 3 && psql -p {{ pg_port }} -c "SELECT pg_xlog_location_diff(pg_current_xlog_insert_location(), flush_location) AS lag_bytes, pid, application_name FROM pg_stat_replication;"
  register: lag

- debug: var=lag.stdout_lines
