---
- name: edit hosts
  lineinfile: dest=/etc/hosts line={{ item }}
  with_items:
    - "{{ pg_slave }}   pg-slave"
    - "{{ pg_master }}   pg-master"
    - "{{ pg_appaddr }}   pg-app"

- name: edit postgresql.conf
  lineinfile: dest=/etc/postgresql/{{ pg_version}}/main/postgresql.conf line={{ item }}
  with_items:
    - "wal_level = 'logical'"
    - "max_worker_processes = 10"
    - "max_replication_slots = 10"
    - "max_wal_senders = 10"
    - "shared_preload_libraries = 'pglogical'"

- name: edit listen adress
  lineinfile: dest=/etc/postgresql/{{ pg_version}}/main/postgresql.conf regexp={{ item.re }} line={{ item.line }}
  with_items:
    - { re: ".*listen_addresses = .*", line: "listen_addresses = '*'" }
    - { re: "^port = .*", line: "port = {{ pg_port }}" }

- name: edit pg_hba.conf
  lineinfile: dest=/etc/postgresql/{{ pg_version}}/main/pg_hba.conf line={{ item }}
  with_items:
    - "host    replication     postgres        pg-slave                trust"
    - "host    replication     postgres        pg-master               trust"
    - "host    app_db          postgres        pg-slave                trust"
    - "host    app_db          postgres        pg-master               trust"
    - "host    app_db          postgres        pg-app                  trust"

- name: restart pg
  service: name=postgresql state=restarted
